import = [ "~/.config/alacritty/themes/themes/hyper.toml" ]

[window]
decorations = "None"
opacity = 0.87
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[font]
size = 12.0
normal = { family = "Hack Nerdfont Mono", style = "Regular" }
